### PR TITLE
spec: Add requirement to util-linux-systemd for wicked-service (bsc#911310)

### PR DESCRIPTION
**Pull request by pwieczorkiewicz**

### CODE REVIEW

**Comment by mtomaschewski** [comment]
a pre-req, see bug report. on update, there are old sysconfig scripts which we execute while migration.
I'd even add a prereq to wicked package already, because our ifup wrapper scripts use logger too....

**Comment by mtomaschewski** [comment]
note also, that this is just about an error message generated by old packages -- does not cause any harm. -> low prio.

**Comment by pwieczorkiewicz** [comment]
Yes. Applied changes and corrections as suggested. Putting on hold for now.

**Comment by mtomaschewski** [comment]
I'd say let's accept it -- it should not hurt, just ensures that the correct package providing logger is installed before wicked.

**Pull request merged**
