### PR TITLE
dhcp4: add DHCLIENT_CREATE_CID to ifcfg (jsc#SLE-15770)

### PR DESCRIPTION
**Pull request by mtomaschewski**
Overrides the DHCPv4 client-identifier type to use specified in the
wicked-config(5) `create-cid` option, the interface type specific
client-id type and compile time defaults.
Note: DHCP over Infiniband (IPoIB) mandates an rfc4361 client-id.

### CODE REVIEW

**Comment by rtorrero** [comment]
Shouldn't we also add a description for DHCLIENT_CREATE_CID in `man ifcfg-dhcp` ?

**Comment by mtomaschewski** [comment]
> Shouldn't we also add a description for DHCLIENT_CREATE_CID in `man ifcfg-dhcp` ?

Yes, done. And fixed the issues (we've never checked result of the parsing function before...).

**Comment by rtorrero** [comment]
Yes, I noticed that DHCLIENT_CREATE_CID was not being parsed correctly. Going to re-test now.

> > Shouldn't we also add a description for DHCLIENT_CREATE_CID in `man ifcfg-dhcp` ?
> 
> Yes, done. And fixed the issues (we've never checked result of the parsing function before...).

**Comment by rtorrero** [comment]
OK, iIve retested with tcpdump & wireshark and it works perfectly now. Also the man page section is there now. LGTM, thanks!

**Review by rtorrero — APPROVED** [review]
LGTM

**Pull request merged**
