### PR TITLE
dhcp4: nullify defer timer pointer when timeout

### LINKED ISSUE #798: dhcp4 fsm timer is abnormally cancelled while validating lease
There're several interfaces in my system, and all of the ifcfg files have these two options:
```
BOOTPROTO='dhcp'
STARTMODE='auto'
```
So all interfaces should be set up simultaneously after reboot.
I continuously reboot the system and check if the eth0 is brought up.
Sometimes I found that the eth0 cannot be up and hangs in setup-in-progress status.
I checked the system message with the WICKED_LOG_LEVEL=debug3 config, and it looks that eth0's timer used to timeout validating state is abnormally cancelled by other interface, say eth6, so that the eth0 is trapped in the validating state.
Please search eth0's fsm timer 0x5593c13d1770 in the following log:
```
Jun 04 08:44:45.579522 DL380G10R3S12 wickedd-dhcp4[1368]: eth0: setting fsm timeout to 200 msec
Jun 04 08:44:45.579543 DL380G10R3S12 wickedd-dhcp4[1368]: ni_timer_register: new timer 0x5593c13d1770 id 1e, callback 0x7f2431562e70/0x5593c13ce870
Jun 04 08:44:45.579562 DL380G10R3S12 wickedd-dhcp4[1368]: __ni_timer_arm: timer 0x5593c13d1770 timeout 200
Jun 04 08:44:45.579577 DL380G10R3S12 wickedd-dhcp4[1368]: ni_timer_next_timeout: timer 0x5593c133ef00 timeout 96
Jun 04 08:44:45.579614 DL380G10R3S12 wickedd-dhcp4[1368]: eth6: incoming arp packet
Jun 04 08:44:45.579635 DL380G10R3S12 wickedd-dhcp4[1368]: eth7: incoming arp packet
Jun 04 08:44:45.579650 DL380G10R3S12 wickedd-dhcp4[1368]: ni_timer_next_timeout: timer 0x5593c133ef00 timeout 96
Jun 04 08:44:45.675867 DL380G10R3S12 wickedd-dhcp4[1368]: ni_timer_next_timeout: timer 0x5593c133ef00 expired (now=1559655885.675830, expires=1559655885.675692)
Jun 04 08:44:45.675888 DL380G10R3S12 wickedd-dhcp4[1368]: eth6: timeout in state VALIDATING
Jun 04 08:44:45.675905 DL380G10R3S12 wickedd-dhcp4[1368]: eth6: Successfully validated DHCPv4 address 20.10.24.48
Jun 04 08:44:45.688121 DL380G10R3S12 wickedd-dhcp4[1368]: eth6: committing lease
Jun 04 08:44:45.688143 DL380G10R3S12 wickedd-dhcp4[1368]: __ni_timer_disarm: timer 0x5593c13d1770 found
Jun 04 08:44:45.688156 DL380G10R3S12 wickedd-dhcp4[1368]: ni_timer_cancel: released timer 0x5593c13d1770
Jun 04 08:44:45.688170 DL380G10R3S12 wickedd-dhcp4[1368]: eth6: schedule renewal of lease in 345600 seconds
Jun 04 08:44:45.688182 DL380G10R3S12 wickedd-dhcp4[1368]: eth6: setting fsm timeout to 345600000 msec
```
eth6's defer timer points to eth0's fsm timer (0x5593c13d1770).

### PR DESCRIPTION
**Pull request by ken23421**
fix #798

### CODE REVIEW

**Comment by mtomaschewski** [comment]
Thanks, good catch!

**Comment by ken23421** [comment]
Thanks @mtomaschewski
BTW, since I'm a SLES user, will this fix be merged to SLES?

**Comment by rtorrero** [comment]
@ken23421 thanks for the PR!.

Yes, since this has been merged to master, it will go to SLES versions which are still supported at some point in the future as an update.

**Comment by ken23421** [comment]
Understood. Thanks @rtorrero :)

**Pull request merged**
