### PR TITLE
remove port arrays and cleanup interface dependencies (bsc#1205604)

### PR DESCRIPTION
**Pull request by mtomaschewski**
- Remove port arrays from bond,team,bridge,ovs-bridge and consistently
  use config and state info attached to the port interface as in
  rtnetlink(7).
- Cleanup ifcfg parsing, schema configuration and service properties
- Migrate ports in xml config and policies already applied in nanny
- Remove "missed config" generation from finite state machine, which is
  is completed while parsing the config or while xml config migration.
- Issue a warning when "lower" interface (e.g. eth0) config is missed
  while parsing config depending on it (e.g. eth0.42 vlan).
- Resolve ovs master to the effective bridge in config and wickedd
- Implement netif-check-state require checks using system relations
  from wickedd/kernel instead of config relations for ifdown and add
  linkDown and deleteDevice checks to all master and lower references.
- Add a `wicked <ifup|ifdown|ifreload> --dry-run …` option to show the
  system/config interface hierarchies as notice with +/- marked
  interfaces to setup and/or shutdown.

### CODE REVIEW

**Comment by mtomaschewski** [comment]
Fixed an issue causing to report errors (and twice) when a blacklisted ifcfg files like `*.bak` created by firewalld exists:
```
Oct 20 11:32:39 install wicked[4871]: Rejecting blacklisted ifcfg-file: /etc/sysconfig/network/ifcfg-ens4.bak
Oct 20 11:32:39 install wicked[4871]: Failed to read ifcfg-file '/etc/sysconfig/network/ifcfg-ens4.bak': No such file or directory
```

**Comment by mtomaschewski** [comment]
The commit 8c1631b is an issue that happens also with master, this branch increases it's probability.

**Comment by cfconrad** [comment]
hi, @JeffreyCheung sorry for not been transparent here, but @mtomaschewski and I are working heavily on this PR offline. As you can imaging this big change need a lot of testings (manual and automated). So plz stay tuned we are on it!

**Comment by JeffreyCheung** [comment]
Thank @cfconrad , very much appreciated :)

**Review by cfconrad — APPROVED** [review]
These changes looks good to me :partying_face:

A test package for SLES, Leap and Tumbleweed is available on obs [network:wicked:testing/wicked](https://build.opensuse.org/package/show/network:wicked:testing/wicked).

**Pull request merged**
